---
resources:
- name: selenium-git-repo
  type: git
  source:
    uri: https://github.com/radavis/selenium-example
    branch: master

jobs:
- name: run-selenium-tests
  plan:
  - get: selenium-git-repo
    trigger: true
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: radavis/java-chromedriver
          tag: latest
      inputs:
        - name: selenium-git-repo
      caches:
        - path: .gradle/
      run:
        path: selenium-git-repo/ci/test.sh
